### ISSUE TITLE
Add command palette action for opening visualiser

### ISSUE THREAD

**Issue by damiensedgwick** [mattpocock/vscode-xstate-demo#14]
As highlighted by another issue #7; If code lens is not enabled, the clickable magnifying glass will not be visible for users to click on and open the visualiser.

To get around this, a command could be added so that the visualiser can be opened from a command palette shortcut. For example: `cmd/ctrl + shift + p` and then entering a command such as `visualiser` or `start vis`.

**Comment by mattpocock** [comment]
Added in 1.1.13!
