### ISSUE TITLE
[Future] Support .tsx, .vue and other extensions?

### ISSUE THREAD

**Issue by santicros** [mattpocock/vscode-xstate-demo#2]
I was testing some machines and the extension wasn't working. I've seen the problem was that it wasn't a js or ts file.

Just an idea for the future, I know now it's still very early :)

**Comment by mattpocock** [comment]
Nice! Should be possible! I haven't tested in any .tsx files, that's a simple addition.

**Comment by mattpocock** [comment]
@santicros Can you test 1.1.1? It should now support .tsx

**Comment by santicros** [comment]
Working great with .tsx @mattpocock! Thanks ;)
