### ISSUE TITLE
Unable to evaluate serialized guards in eventless transitions

### ISSUE THREAD

**Issue by janovekj** [mattpocock/vscode-xstate-demo#5]
The following code yields the error
```
Unable to evaluate guard 'test' in transition for event '' in state node '(machine).someState':
guard.predicate is not a function
```

```ts
createMachine(
  {
    initial: "someState", // also, the error disappears if the machine doesn't have an initial state 🤔
    states: {
      someState: {
        always: { cond: "test", target: "otherState" },
      },
      otherState: {},
    },
  },
  {
    guards: {
      test: () => true,
    },
  }
);
```

It works fine if I inline the guard instead. Also, serialized guards works fine in regular event transitions.

**Comment by mattpocock** [comment]
@janovekj Thanks for this, noticed this myself and have a fix in the pipeline.

**Comment by janovekj** [comment]
> @janovekj Thanks for this, noticed this myself and have a fix in the pipeline.

Neat, thanks 👍

**Comment by mattpocock** [comment]
We can consider this closed as of the latest release, appears to be working now.
