### ISSUE TITLE
Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by josmithua** [mattpocock/vscode-xstate-demo#6]
I'm getting `Maximum call stack size exceeded` error when using `always` to go back and forth between states, even though they have `cond`s:

```js
    states: {
      noneSelected: {
        always: {
          target: 'someSelected',
          cond: (ctx) => ctx.selected.length > 0,
        },
      },
      someSelected: {
        on: {
          PRINT: { actions: 'printSelected' },
          COPY: { actions: 'copySelected' },
          DESELECT_ALL: { actions: 'clearSelected' },
        },
        always: {
          target: 'noneSelected',
          cond: (ctx) => ctx.selected.length === 0,
        },
      },
    },
```

**Comment by damiensedgwick** [comment]
> I'm getting `Maximum call stack size exceeded` error when using `always` to go back and forth between states, even though they have `cond`s:
> 
> ```js
>     states: {
>       noneSelected: {
>         always: {
>           target: 'someSelected',
>           cond: (ctx) => ctx.selected.length > 0,
>         },
>       },
>       someSelected: {
>         on: {
>           PRINT: { actions: 'printSelected' },
>           COPY: { actions: 'copySelected' },
>           DESELECT_ALL: { actions: 'clearSelected' },
>         },
>         always: {
>           target: 'noneSelected',
>           cond: (ctx) => ctx.selected.length === 0,
>         },
>       },
>     },
> ```

Do you mind sharing the whole machine or saving it and sharing a link to it please?

**Comment by josmithua** [comment]
Hi Damien, I just tried it again and it seems the errors are gone. Here's the link anyways: https://stately.ai/viz/546432e7-c837-46fa-94f8-7c430ffb5493

**Comment by damiensedgwick** [comment]
> Hi Damien, I just tried it again and it seems the errors are gone. Here's the link anyways: https://stately.ai/viz/546432e7-c837-46fa-94f8-7c430ffb5493

My work here is done 🤣

**Comment by josmithua** [comment]
Amazing, thank you 🤣
