### ISSUE TITLE
"Open Inspector" never shows

### ISSUE THREAD

**Issue by parker-codes** [mattpocock/vscode-xstate-demo#7]
After installing the extension and visiting machine files, no "Open Inspector" link shows. I restarted VSCode for good measure. I even attempted different machines (I have quite a few).

I'm on MacOS Big Sur on an M1 architecture.

Here's an obfuscated version of the machine:

```ts
import { assign, createMachine } from "xstate";

export const dashboardMachine = createMachine(
  {
    id: "dashboard",
    initial: "inactive",

    context: {
      list1: [],
      list2: [],
    },

    states: {
      inactive: {
        on: {
          ENTER: "active",
        },
      },

      active: {
        type: "parallel",

        on: {
          EXIT: "inactive",
        },

        states: {
          list1: {
            initial: "loading",

            states: {
              loading: {
                invoke: {
                  src: "fetchList1",
                  onDone: {
                    target: "idle",
                    actions: ["assignList1"],
                  },
                  onError: "errorLoading",
                },
              },
              errorLoading: {},
              idle: {},
            },
          },

          list2: {
            initial: "loading",

            states: {
              loading: {
                invoke: {
                  src: "fetchList2",
                  onDone: {
                    target: "idle",
                    actions: ["assignList2"],
                  },
                  onError: "errorLoading",
                },
              },
              errorLoading: {},
              idle: {},
            },
          },
        },
      },
    },
  },

  /*
   * Options
   */
  {
    actions: {
      assignList1: assign((context, event) => ({
        // @ts-expect-error
        list1: event.data,
      })),
      assignList2: assign((context, event) => ({
        // @ts-expect-error
        list2: event.data,
      })),
    },

    services: {
      fetchList1: async (context, event) => {
        return ['first', 'list'];
      },
      fetchList2: async (context, event) => {
        return ['second', 'list'];
      },
    },
  }
);
```

**Comment by mattpocock** [comment]
Strange, it's showing it for me! Copied and pasted into a new file and it's working.

**Comment by mattpocock** [comment]
![image](https://user-images.githubusercontent.com/28293365/132258473-b536cfc7-76ca-4aee-b1e3-3f67ee87cf02.png)

**Comment by damiensedgwick** [comment]
is it to do with file name, e.g does the file have to follow a pattern such as `filename.machine.ts` or will it pick up a machine in `filenameMachine.ts`? Might not be the issue just throwing up ideas.

**Comment by mattpocock** [comment]
Nope, no filename restriction!

**Comment by damiensedgwick** [comment]
That's me all out of ideas on that one then 😅

**Comment by parker-codes** [comment]
It was figured out in Discord (yesterday, I think). You have to enable Code Lens for the prompt to appear over the machine definition. 

I just tested it and it works! The problem is, I don't like the clutter of Code Lens so this means I have to toggle it in settings before/after using the extension visualizer.

**Comment by damiensedgwick** [comment]
it would be good to have a command to open the visualiser also I think @mattpocock for those who aren't a fan of the code lense?

**Comment by mattpocock** [comment]
@damiensedgwick 100%! Could you add an issue?

**Comment by damiensedgwick** [comment]
> @damiensedgwick 100%! Could you add an issue?

Certainly!

**Comment by mattpocock** [comment]
It looks like we can close this issue - looks like a code lens thing.
